config/routes.rb
Rails.application.routes.draw do
  post 'account/login'
  get 'account/logout'
  get 'account/login_page'

  root :to => "static#index"

  resources :users do
    resources :companies, only: [:index, :new, :create]
  end
  resources :companies, only: [:show, :edit, :update, :destroy]

  resources :products, :product_types, :company_products

end

app/models/company_product.rb
class CompanyProduct < ActiveRecord::Base
  validates :product_id, uniqueness: { scope: :company_id,
    message: "One kind of product permitted per company" }
      
  belongs_to :company
  belongs_to :product
end

app/controllers/company_products_controller.rb
class CompanyProductsController < ApplicationController
  before_action :set_company_product, only: [:show, :edit, :update, :destroy]

  # GET /company_products
  # GET /company_products.json
  def index
    @company_products = CompanyProduct.all
  end

  # GET /company_products/1
  # GET /company_products/1.json
  def show
  end

  # GET /company_products/new
  def new
    @company_product = CompanyProduct.new
  end

  # GET /company_products/1/edit
  def edit
  end

  # POST /company_products
  # POST /company_products.json
  def create
    @company_product = CompanyProduct.new(company_product_params)

    respond_to do |format|
      if @company_product.save
        format.html { redirect_to @company_product, notice: 'Company product was successfully created.' }
        format.json { render :show, status: :created, location: @company_product }
      else
        format.html { render :new }
        format.json { render json: @company_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_products/1
  # PATCH/PUT /company_products/1.json
  def update
    respond_to do |format|
      if @company_product.update(company_product_params)
        format.html { redirect_to @company_product, notice: 'Company product was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_product }
      else
        format.html { render :edit }
        format.json { render json: @company_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_products/1
  # DELETE /company_products/1.json
  def destroy
    @company_product.destroy
    respond_to do |format|
      format.html { redirect_to company_products_url, notice: 'Company product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_product
      @company_product = CompanyProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_product_params
      params.require(:company_product).permit(:product_id, :company_id, :quantity, :quantity_unit, :price, :price_unit)
    end
end

app/helpers/company_products_helper.rb
module CompanyProductsHelper
end

app/views/company_products/_form.html.erb
<%= form_for(@company_product) do |f| %>
  <% if @company_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_product.errors.count, "error") %> prohibited this company_product from being saved:</h2>

      <ul>
      <% @company_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :quantity_unit %><br>
    <%= f.text_field :quantity_unit %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :price_unit %><br>
    <%= f.text_field :price_unit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company_products/edit.html.erb
<h1>Editing company_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_product %> |
<%= link_to 'Back', company_products_path %>

app/views/company_products/index.html.erb
<h1>Listing company_products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Company</th>
      <th>Quantity</th>
      <th>Quantity unit</th>
      <th>Price</th>
      <th>Price unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_products.each do |company_product| %>
      <tr>
        <td><%= company_product.product_id %></td>
        <td><%= company_product.company_id %></td>
        <td><%= company_product.quantity %></td>
        <td><%= company_product.quantity_unit %></td>
        <td><%= company_product.price %></td>
        <td><%= company_product.price_unit %></td>
        <td><%= link_to 'Show', company_product %></td>
        <td><%= link_to 'Edit', edit_company_product_path(company_product) %></td>
        <td><%= link_to 'Destroy', company_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company product', new_company_product_path %>

app/views/company_products/new.html.erb
<h1>New company_product</h1>

<%= render 'form' %>

<%= link_to 'Back', company_products_path %>

app/views/company_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @company_product.product_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @company_product.company_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @company_product.quantity %>
</p>

<p>
  <strong>Quantity unit:</strong>
  <%= @company_product.quantity_unit %>
</p>

<p>
  <strong>Price:</strong>
  <%= @company_product.price %>
</p>

<p>
  <strong>Price unit:</strong>
  <%= @company_product.price_unit %>
</p>

<%= link_to 'Edit', edit_company_product_path(@company_product) %> |
<%= link_to 'Back', company_products_path %>